# Generated by Django 3.2.5 on 2021-11-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONJURE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CR', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Monster',
        ),
    ]
